---
- hosts: 127.0.0.1
  connection: local
  tasks:
  - nova_compute:
       state: present
       auth_url: {{ endpoint }}
       login_username: {{ admin_user }}
       login_password: {{ admin_password }}
       login_tenant_name: {{ admin_tenant }}
       name: {{ name }}
       image_id: {{ image_id }}
       key_name: ansible_key
       wait_for: 200
       flavor_id: {{ flavor_id }}
       nics:
         - net-id: {{ net_id }}
       meta:
         hostname: test1
         group: uge_master
  - keystone_user: endpoint={{ endpoint }} user="{{ name }}" email={{ email }} password={{ password }} login_user={{ admin_user }} login_password={{ admin_password }} login_tenant_name={{ admin_tenant }} tenant={{ tenant }}
  {% for role in roles %}
  - keystone_user: endpoint={{ endpoint}} login_user={{ admin_user }} login_password={{ admin_password }} login_tenant_name={{ admin_tenant }} user="{{ name }}" role={{ role }} tenant={{ tenant }}
  {% endfor %}
